export type SettingStatus = 'ready' | 'recommended' | 'planned' | 'sensitive';

export type SettingsOption = {
  key: string;
  title: string;
  subtitle: string;
  description: string;
  group: string;
  icon: string;
  status: SettingStatus;
  href?: string;
  columns?: string[];
  source?: 'profiles' | 'subscriptions' | 'uslife_invites' | 'plan_interest_requests';
};

export const settingsGroups = [
  'Conta',
  'Perfil',
  'Privacidade',
  'Experiência',
  'Personalização',
  'Dados',
  'Produto',
  'Sistema',
];

export const settingsOptions: SettingsOption[] = [
  {
    key: 'account',
    title: 'Conta',
    subtitle: 'Identidade da conta.',
    description: 'Dados centrais da conta e campos estruturais do perfil.',
    group: 'Conta',
    icon: 'UserRound',
    status: 'ready',
    source: 'profiles',
    columns: ['id', 'full_name', 'first_name', 'social_name', 'username', 'birth_date', 'country', 'language'],
  },
  {
    key: 'security',
    title: 'Segurança',
    subtitle: 'Sessão e proteção.',
    description: 'Área sensível para sessão, login, senha e proteção da conta.',
    group: 'Conta',
    icon: 'ShieldCheck',
    status: 'sensitive',
    source: 'profiles',
    columns: ['id', 'created_at', 'updated_at'],
  },
  {
    key: 'profile',
    title: 'Perfil essencial',
    subtitle: 'Nome, nascimento e username.',
    description: 'Edite os dados essenciais usados para identificar seu espaço.',
    group: 'Perfil',
    icon: 'BadgeCheck',
    status: 'ready',
    href: '/onboarding/basic-info?edit=1',
    source: 'profiles',
    columns: ['full_name', 'first_name', 'social_name', 'birth_date', 'username'],
  },
  {
    key: 'media',
    title: 'Avatar e capa',
    subtitle: 'Imagem e identidade visual.',
    description: 'Configure imagem de perfil, capa e símbolo visual.',
    group: 'Perfil',
    icon: 'Image',
    status: 'recommended',
    href: '/onboarding/avatar',
    source: 'profiles',
    columns: ['avatar_url', 'cover_url', 'color_symbol'],
  },
  {
    key: 'flora',
    title: 'Flora',
    subtitle: 'Espécie, estágio e inclinação.',
    description: 'Campos originais da identidade viva da IRIS.',
    group: 'Personalização',
    icon: 'Leaf',
    status: 'ready',
    source: 'profiles',
    columns: ['especie', 'estagio', 'inclinacao'],
  },
  {
    key: 'personality',
    title: 'Personalidade',
    subtitle: 'Como a IRIS entende você.',
    description: 'Sinais de personalidade, energia, percepção, decisão e ritmo social.',
    group: 'Personalização',
    icon: 'Brain',
    status: 'recommended',
    href: '/onboarding/personality',
    source: 'profiles',
    columns: ['personality_data', 'personality_completed_at'],
  },
  {
    key: 'culture',
    title: 'Cultura',
    subtitle: 'Temas e repertório.',
    description: 'Temas culturais, formatos preferidos, tom e ritmo da experiência.',
    group: 'Personalização',
    icon: 'Sparkles',
    status: 'recommended',
    href: '/onboarding/culture',
    source: 'profiles',
    columns: ['culture_tags', 'culture_data', 'culture_completed_at'],
  },
  {
    key: 'intention',
    title: 'Intenção',
    subtitle: 'Direção da experiência.',
    description: 'O que a IRIS deve priorizar na experiência do usuário.',
    group: 'Personalização',
    icon: 'Compass',
    status: 'recommended',
    href: '/onboarding/intention',
    source: 'profiles',
    columns: ['intention', 'intention_data', 'intention_completed_at'],
  },
  {
    key: 'privacy',
    title: 'Privacidade',
    subtitle: 'Visibilidade e limites.',
    description: 'Controle privacidade, memórias, IA e proteções extras.',
    group: 'Privacidade',
    icon: 'LockKeyhole',
    status: 'recommended',
    href: '/onboarding/privacy',
    source: 'profiles',
    columns: ['privacy_level', 'privacy_data', 'privacy_completed_at'],
  },
  {
    key: 'accessibility',
    title: 'Acessibilidade',
    subtitle: 'Tema, fonte e leitura.',
    description: 'Tema, dislexia, tamanho da fonte, espaçamento, contraste e movimento.',
    group: 'Experiência',
    icon: 'Accessibility',
    status: 'ready',
    href: '/onboarding/accessibility',
    source: 'profiles',
    columns: ['accessibility_data', 'accessibility_completed_at', 'theme_preference'],
  },
  {
    key: 'appearance',
    title: 'Aparência',
    subtitle: 'Tema visual.',
    description: 'Preferência visual principal da experiência.',
    group: 'Experiência',
    icon: 'Palette',
    status: 'ready',
    href: '/onboarding/accessibility',
    source: 'profiles',
    columns: ['theme_preference', 'accessibility_data'],
  },
  {
    key: 'integrations',
    title: 'Integrações',
    subtitle: 'Conexões futuras.',
    description: 'Preferências de calendário, fotos, contatos, localização, e-mail e arquivos.',
    group: 'Dados',
    icon: 'Plug',
    status: 'planned',
    href: '/onboarding/integrations',
    source: 'profiles',
    columns: ['integration_preferences', 'integration_data', 'integrations_completed_at'],
  },
  {
    key: 'subscription',
    title: 'Assinatura',
    subtitle: 'Plano ativo e ciclo.',
    description: 'Dados da tabela subscriptions: plano, status, trial e período atual.',
    group: 'Produto',
    icon: 'CreditCard',
    status: 'ready',
    source: 'subscriptions',
    columns: ['plan', 'status', 'trial_ends_at', 'current_period_ends_at', 'created_at', 'updated_at'],
  },
  {
    key: 'plan',
    title: 'Plano escolhido',
    subtitle: 'Preferência do onboarding.',
    description: 'Preferência de plano, ciclo, código e interesse sob demanda.',
    group: 'Produto',
    icon: 'Crown',
    status: 'ready',
    href: '/onboarding/plan',
    source: 'profiles',
    columns: ['plan_key', 'plan_data', 'plan_completed_at'],
  },
  {
    key: 'uslife',
    title: 'usLIFE',
    subtitle: 'Convites e espaço compartilhado.',
    description: 'Preferências de convite, vínculo e permissões usLIFE.',
    group: 'Produto',
    icon: 'HeartHandshake',
    status: 'recommended',
    href: '/onboarding/uslife-invite',
    source: 'profiles',
    columns: ['uslife_invite_data', 'uslife_invite_completed_at'],
  },
  {
    key: 'completion',
    title: 'Conclusão do perfil',
    subtitle: 'Selo e tema gratuito.',
    description: 'Progresso do perfil, recompensa, badges e temas desbloqueados.',
    group: 'Produto',
    icon: 'Gift',
    status: 'ready',
    source: 'profiles',
    columns: ['onboarding_status', 'onboarding_completed', 'profile_completion_status', 'profile_completion_reward_status', 'profile_badges', 'unlocked_themes'],
  },
  {
    key: 'data',
    title: 'Dados e exportação',
    subtitle: 'Controle dos dados.',
    description: 'Área futura para exportar, apagar e revisar dados.',
    group: 'Dados',
    icon: 'Database',
    status: 'planned',
  },
  {
    key: 'notifications',
    title: 'Notificações',
    subtitle: 'Alertas e lembretes.',
    description: 'Configuração futura de push, e-mail, lembretes e modo silencioso.',
    group: 'Sistema',
    icon: 'Bell',
    status: 'planned',
  },
  {
    key: 'diagnostics',
    title: 'Diagnóstico',
    subtitle: 'Debug e ambiente.',
    description: 'Área técnica para sessão, cache, Supabase e integridade.',
    group: 'Sistema',
    icon: 'Activity',
    status: 'planned',
  },
];

export const quickSettingsKeys = [
  'profile',
  'media',
  'privacy',
  'accessibility',
  'personality',
  'culture',
  'intention',
  'subscription',
  'uslife',
  'plan',
  'completion',
  'flora',
  'appearance',
  'integrations',
  'data',
  'notifications',
];

export function getSettingByKey(key: string) {
  return settingsOptions.find((option) => option.key === key) || settingsOptions[0];
}

export function getQuickSettings() {
  return quickSettingsKeys.map((key) => getSettingByKey(key)).filter(Boolean);
}
