/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class', '[data-theme="dark"]'],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        iris: {
          forest: '#1B3A2E',
          emerald: '#006D4E',
          lilac: '#9A7CA7',
          black: '#111111',
          offWhite: '#FAF7F2',
          sage: {
            light: '#DDE6DA',
            medium: '#B9C8B5',
          },
          sand: '#EDE6DA',
          rose: '#EAD8D6',
          lavender: '#D7D4E6',
          mist: '#D6DEE6',
        },
        neutral: {
          100: '#F2F4F3',
          200: '#E3E7E6',
          300: '#C7CFCC',
          400: '#9AA4A1',
          500: '#747D79',
          600: '#4F5955',
          700: '#2A3430',
          800: '#161E1A',
          900: '#0F1512',
        },
        // Cores com suporte a opacidade (para from-emerald/20 etc.)
        emerald: {
          50: '#e6f7f0',
          100: '#cceee1',
          200: '#99ddc3',
          300: '#66cca5',
          400: '#33bb87',
          500: '#006D4E', // padrão
          600: '#00573e',
          700: '#00412e',
          800: '#002c1f',
          900: '#00160f',
          DEFAULT: '#006D4E',
        },
        emotion: {
          DEFAULT: '#9A7CA7',
          50: '#f5f0f7',
          100: '#ebe1ef',
          200: '#d7c3df',
          300: '#c3a5cf',
          400: '#af87bf',
          500: '#9A7CA7',
          600: '#7b6386',
          700: '#5c4a64',
          800: '#3e3243',
          900: '#1f1922',
        },
        accent: {
          DEFAULT: 'var(--color-accent)',
          hover: 'var(--color-accent-hover)',
          subtle: 'var(--color-accent-subtle)',
        },
        background: {
          primary: 'var(--color-bg-primary)',
          surface: 'var(--color-bg-surface)',
          subtle: 'var(--color-bg-subtle)',
        },
        text: {
          primary: 'var(--color-text-primary)',
          secondary: 'var(--color-text-secondary)',
          muted: 'var(--color-text-muted)',
          inverse: 'var(--color-text-inverse)',
        },
        border: {
          DEFAULT: 'var(--color-border)',
          strong: 'var(--color-border-strong)',
        },
        success: 'var(--color-success)',
        warning: 'var(--color-warning)',
        danger: 'var(--color-danger)',
        info: 'var(--color-info)',
      },
      fontFamily: {
        display: ['Playfair Display', 'serif'],
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        accessible: ['OpenDyslexic', 'sans-serif'],
      },
      fontSize: {
        'display': ['var(--text-display-size)', { lineHeight: 'var(--text-display-line)' }],
        'h1': ['var(--text-h1-size)', { lineHeight: 'var(--text-h1-line)' }],
        'h2': ['var(--text-h2-size)', { lineHeight: 'var(--text-h2-line)' }],
        'h3': ['var(--text-h3-size)', { lineHeight: 'var(--text-h3-line)' }],
        'lg': ['var(--text-lg-size)', { lineHeight: 'var(--text-lg-line)' }],
        'base': ['var(--text-base-size)', { lineHeight: 'var(--text-base-line)' }],
        'sm': ['var(--text-sm-size)', { lineHeight: 'var(--text-sm-line)' }],
        'xs': ['var(--text-xs-size)', { lineHeight: 'var(--text-xs-line)' }],
      },
      spacing: {
        '1': 'var(--space-1)',
        '2': 'var(--space-2)',
        '3': 'var(--space-3)',
        '4': 'var(--space-4)',
        '6': 'var(--space-6)',
        '8': 'var(--space-8)',
        '12': 'var(--space-12)',
        '16': 'var(--space-16)',
        '24': 'var(--space-24)',
      },
      borderRadius: {
        'none': 'var(--radius-none)',
        'sm': 'var(--radius-sm)',
        'md': 'var(--radius-md)',
        'lg': 'var(--radius-lg)',
        'xl': 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
      },
      boxShadow: {
        'sm': 'var(--shadow-sm)',
        'md': 'var(--shadow-md)',
        'lg': 'var(--shadow-lg)',
        'xl': 'var(--shadow-xl)',
      },
      zIndex: {
        'base': 'var(--z-base)',
        'header': 'var(--z-header)',
        'dropdown': 'var(--z-dropdown)',
        'sticky': 'var(--z-sticky)',
        'overlay': 'var(--z-overlay)',
        'modal': 'var(--z-modal)',
        'toast': 'var(--z-toast)',
        'aurora': 'var(--z-aurora)',
      },
      transitionDuration: {
        'fast': 'var(--duration-fast)',
        'base': 'var(--duration-base)',
        'slow': 'var(--duration-slow)',
        'emotional': 'var(--duration-emotional)',
      },
      transitionTimingFunction: {
        'out-soft': 'var(--ease-out-soft)',
      },
    },
  },
  plugins: [],
}